/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/worker-configuration.d.ts` (hash: 98b034bb5d7505dccdf90156043a7698)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
