/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/worker-configuration.d.ts` (hash: b49002633c8a13e1566e85bc6c419f3e)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	MEDIA: R2Bucket;
	DB: D1Database;
	WEB_ORIGIN: "https://todos.remics.tech";
	MCP_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEB_ORIGIN" | "MCP_TOKEN">> {}
}
