/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/worker-configuration.d.ts` (hash: fa7c657872ca54cafdf548c18efd49ad)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	MEDIA: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
